@PROTOCOL = {{$dotenv API_PROTOCOL}}
@HOST = {{$dotenv AI_TRUST_HOST}}
@PROJECT = {{$dotenv PROJECT_ID}}
@TOKEN = {{$dotenv API_TOKEN}}
@SERVICE = vps
@BASE_URL = {{PROTOCOL}}://{{HOST}}/{{SERVICE}}/api/v1/project/{{PROJECT}}


### Create KeyPair
# @name KeypairCreate
POST {{BASE_URL}}/keypairs HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
    "name": "test-keypair"
}

@testKeypairId={{KeypairCreate.response.body.$.id}}
@errorCode={{KeypairCreate.response.body.$.errorCode}}

### Lis tKeyPair
# @name KeypairList
GET {{BASE_URL}}/keypairs HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}


### Get Specific Keypair
# @name KeypairGet
GET {{BASE_URL}}/keypairs/{{testKeypairId}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}


### Update Keypair
# @name KeypairUpdate
PUT {{BASE_URL}}/keypairs/{{testKeypairId}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}

{
    "description": "new-description"
}

### Delete keypair
# @name KeypairDelete
DELETE {{BASE_URL}}/keypairs/{{testKeypairId}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{TOKEN}}

